# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /blog/:categories/:year/:month/:day/:title/

# Setup
title:               Atrenko
tagline:             Agile Architecture Consultancy
url:                 http://www.atrenko.com
logo:                /public/images/logo.svg
description:         Atrenko provides agile architecture and development services on a freelance basis.
paginate:            10
paginate_path:       "/blog/page:num/"
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jan Sabbe
  url:               https://twitter.com/jansabbe
  email:             info@atrenko.com
  twitter:           jansabbe

# twitter
twitter:
  username: jansabbe

social:
  name: Jan Sabbe
  links:
    - https://twitter.com/jansabbe
    - https://www.linkedin.com/in/jansabbe/
    - https://github.com/jansabbe/

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/jansabbe/jansabbe.github.io

pages_list:
  Home: '/'
  Blog: '/blog/'
  Feed: '/atom.xml'

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  - projects